name: Build (Windows, MSYS2)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-msys2:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-openmp  # optional, if you need OpenMP lib
      - name: Add mingw to PATH
        shell: bash
        run: echo "::add-path::/mingw64/bin"

      - name: Build with g++
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          # compile; adjust file name(s) / flags as needed
          x86_64-w64-mingw32-g++ -fopenmp ParallelCryptography.cpp -O2 -o parallel-cryptography.exe
          ls -l parallel-cryptography.exe
          ./parallel-cryptography.exe || true

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: parallel-cryptography-windows
          path: parallel-cryptography.exe
