name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-msys2:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSYS2 (MINGW64) and install toolchain
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-openmp

      - name: Add mingw64 to PATH
        shell: bash
        run: |
          echo "/mingw64/bin" >> $GITHUB_PATH
          export PATH="/mingw64/bin:$PATH"
          which g++
          g++ --version

      - name: Build binary (g++)
        shell: bash
        run: |
          cd "$GITHUB_WORKSPACE"
          # compile - adjust flags or extra files if needed
          g++ -fopenmp ParallelCryptography.cpp -O2 -o parallel-cryptography.exe
          ls -la parallel-cryptography.exe
          # run with a harmless flag so output appears in logs (prevent CI failure if program returns nonzero)
          ./parallel-cryptography.exe || true

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: parallel-cryptography-windows
          path: parallel-cryptography.exe
