name: CI - Build (Windows)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up MinGW (for g++)
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64

      - name: Build
        run: |
          g++ -fopenmp ParallelCryptography.cpp -o parallel-cryptography.exe -O2
          dir

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: parallel-cryptography-windows
          path: parallel-cryptography.exe
