name: Build & Release (multi-platform)

on:
  push:
    tags:
      - 'v*.*.*'  # e.g. v1.0.0

jobs:
  build-linux:
    runs-on: ubuntu-latest
    outputs:
      artifact: ${{ steps.upload.outputs.artifact-path }}
    steps:
      - uses: actions/checkout@v4
      - name: Install build deps
        run: sudo apt-get update && sudo apt-get install -y build-essential
      - name: Build (Linux)
        run: |
          g++ -fopenmp ParallelCryptography.cpp -O2 -o parallel-cryptography-linux
          ls -la parallel-cryptography-linux
      - name: Upload linux artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: parallel-cryptography-linux
          path: parallel-cryptography-linux

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup MSYS2 and toolchain
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-openmp
      - name: Build (Windows)
        shell: bash
        run: |
          echo "/mingw64/bin" >> $GITHUB_PATH
          g++ -fopenmp ParallelCryptography.cpp -O2 -o parallel-cryptography-windows.exe
          ls -la parallel-cryptography-windows.exe
      - name: Upload windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: parallel-cryptography-windows
          path: parallel-cryptography-windows.exe

  create_release:
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts (Linux)
        uses: actions/download-artifact@v4
        with:
          name: parallel-cryptography-linux
      - name: Download artifacts (Windows)
        uses: actions/download-artifact@v4
        with:
          name: parallel-cryptography-windows
      - name: Create GitHub Release
        id: ghrel
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
      - name: Upload release assets
        uses: ncipollo/release-action@v1
        with:
          files: |
            parallel-cryptography-linux
            parallel-cryptography-windows.exe
